"""Clip model."""
import enum
from datetime import datetime
from sqlalchemy import Column, Integer, String, DateTime, Enum, Float, ForeignKey
from sqlalchemy.orm import relationship

from app.db.database import Base


class ClipSource(str, enum.Enum):
    """Clip creation source."""
    AUTO = "auto"  # Generated by scene detection
    MANUAL = "manual"  # Created/modified by user


class Clip(Base):
    """Clip model representing a segment of the source video."""
    
    __tablename__ = "clips"
    
    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), nullable=False)
    
    # Clip boundaries (in seconds)
    start_time = Column(Float, nullable=False)
    end_time = Column(Float, nullable=False)
    
    # Metadata
    name = Column(String(255), nullable=True)
    thumbnail_path = Column(String(4096), nullable=True)
    created_by = Column(Enum(ClipSource), default=ClipSource.AUTO, nullable=False)
    ordering = Column(Integer, nullable=False, default=0)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    project = relationship("Project", back_populates="clips")
    compound_items = relationship("CompoundClipItem", back_populates="clip", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<Clip(id={self.id}, start={self.start_time:.2f}, end={self.end_time:.2f})>"
    
    @property
    def duration(self):
        """Get clip duration in seconds."""
        return self.end_time - self.start_time
    
    def to_dict(self):
        """Convert to dictionary."""
        return {
            "id": self.id,
            "project_id": self.project_id,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "duration": self.duration,
            "name": self.name,
            "thumbnail_path": self.thumbnail_path,
            "created_by": self.created_by.value,
            "ordering": self.ordering,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

